version: 2.1
environment:
  AZURE_CLIENT_ID: ab795cd7-5b59-4d1d-afb2-fa04b04db278
  AZURE_CLIENT_SECRET: I5K8Q~e14r-IQ9sVcSeWD7g1TzqGLm8zrX8Rjadh
  AZURE_TENANT_ID: adce66e5-0a46-4c70-b26c-98866bb294ea
jobs:
  # build_test:
  #   machine:
  #     image: ubuntu-2004:current
  #   resource_class: large
  #   steps:
  #     - checkout
  #     # Download and cache dependencies
  #     - restore_cache:
  #         keys:
  #           - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "package-lock.json" }}
  #           # Perform a Partial Cache Restore (https://circleci.com/docs/2.0/caching/#restoring-cache)
  #           - v1-dependencies-
  #     - run:
  #         name: Install Java 17
  #         command: |
  #           sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
  #     - run:
  #         name: Set Java 17 as default
  #         command: sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
  #     - run:
  #         name: Print Node Version
  #         command: 'node -v'
  #     - run:
  #         name: Print NPM Version
  #         command: 'npm -v'
  #     - run:
  #         name: Install Node Modules
  #         command: 'npm install'
  #     - save_cache:
  #         paths:
  #           - node
  #           - node_modules
  #           - ~/.m2
  #         key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "package-lock.json" }}

  #     - run:
  #         name: Give Executable Power
  #         command: 'chmod +x mvnw'
  #     - run:
  #         name: Backend tests
  #         command: |
  #           export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
  #           npm run ci:backend:test
  #     - run:
  #         name: Run Front End Tests
  #         command: npm run ci:frontend:test
      # - run:
      #     name: 'E2E: Package'
      #     command: npm run ci:e2e:package
      # - run:
      #     name: 'E2E: Prepare'
      #     command: npm run ci:e2e:prepare
      # - run:
      #     name: 'E2E: Run'
      #     command: npm run ci:e2e:run
      #     environment:
      #       CYPRESS_ENABLE_RECORD: false
      # - run:
      #     name: 'E2E: Teardown'
      #     command: npm run ci:e2e:teardown
  deliver:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run:
          name: Install Java 17
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-17-jdk
      - run: 
          name: Generate JAR
          command: |
            export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64/
            npm run java:jar:prod
      # - persist_to_workspace:
      #     root: .
      #     paths:
      #       - target/proy*.jar
      - store_artifacts:
          path: /home/circleci/project/target/proybaseangmvn-3-0.0.1-SNAPSHOT.jar

  deploy:
    environment:
      AZURE_WEBAPP_PUBLISH_PROFILE: $AZURE_WEBAPP_PUBLISH_PROFILE
    docker:
      - image: "mcr.microsoft.com/azure-cli"
    steps:
      - attach_workspace:
          at: .
      # - run:
      #     name: Install Azure CLI
      #     command: |
      #       curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      - run:
          name: Authenticate with Azure
          command: |
            az login --service-principal --username ab795cd7-5b59-4d1d-afb2-fa04b04db278 --password I5K8Q~e14r-IQ9sVcSeWD7g1TzqGLm8zrX8Rjadh --tenant adce66e5-0a46-4c70-b26c-98866bb294ea
      - run:
          name: Deploy to Azure
          command: |
            az webapp deployment source config-zip -g proybase -n proybaseappservi --src /home/circleci/project/target/proybaseangmvn-3-0.0.1-SNAPSHOT.jar
      # - run: |
      #     az login --service-principal --username "ab795cd7-5b59-4d1d-afb2-fa04b04db278" --password "I5K8Q~e14r-IQ9sVcSeWD7g1TzqGLm8zrX8Rjadh" --tenant "adce66e5-0a46-4c70-b26c-98866bb294ea"
      #     az webapp deploy --name proybaseappservi --slot production --package $(find . -name "proy*.jar") --type java --verbose

workflows:
  version: 2
  sample:
    jobs:
      # - build:
      #       filters:
      #           branches:
      #               only:
      #                   - feature/circleci
      - deliver:
          filters:
              branches:
                  only:
                      - feature/circleci
      - deploy:
          requires:
              - deliver
          filters:
              branches:
                  only:
                      - feature/circleci