apiVersion : apps/v1
kind: Deployment
metadata:
  name: robcruzdproybaseangmvn 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: robcruzdproybaseangmvn
  template:
    metadata:
      labels:
        app: robcruzdproybaseangmvn 
    spec:
      containers:
        - name: robcruzdproybaseangmvn 
          image: proybaseangmvn3.azurecr.io/robcruzdproybaseangmvn
          ports:
          - containerPort: 80